name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2

    - run: npm ci

    - id: test
      run: npm run test
      env:
        CI: true
      continue-on-error: true

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
        directory: ./coverage/
        fail_ci_if_error: true
      if: always()
